config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resources :questions, only: [:index, :show]


  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/users/new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CeleryHatersAnon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header>
    <h1>We hate celery, yes we do</h1>

    <nav>
      <ul>
        <% if session[:user_id] == nil %>
          <li> <%= link_to "Login", login_path %> </li>
          <li> <%= link_to "Register", new_user_path %> </li>
        <% elsif session[:user_id] %>
          <li> <%= button_to "Logout", { action: 'destroy', controller: 'sessions' }, method: :delete  %>
        <% end %>
        </li>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<section>



<% @questions.each do |question| %>

  <div class="">
      <h3> <%= link_to question.topic , question_path(question) %> </h3>
  </div>

<% end %>







</section>

app/views/questions/show.html.erb
<h3><%= @question.topic %></h3>
<p> <%= @question.description %></p>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for :user, url: users_path do |f| %>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label "Password Confirmation"%>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Submit" %>

  </p>
  <% end %>